### ISSUE TITLE
Game fails to compile

### ISSUE THREAD

**Issue by bradleyGamiMarques** [agrnerd17/Breakout-Game#1]
Hi Amelie,

I tried compiling your game after your recent changes and I am still encountering errors. Below is my system setup and the steps that I have tried.

OS: Ubuntu 22.04.3 LTS
Compiler: gcc version 11.4.0
GNU Make 4.3

1. Traverse all directories and subdirectories and run the `make` command on the directories that have a MAKEFILE
2. Find all files with a .cpp extension.
![image](https://github.com/agrnerd17/Breakout-Game/assets/18665288/14100edf-c679-4e91-87a2-bdd12b1d2bcd)
3. Run `find . -name "*.cpp" | xargs g++ -o breakout` To recursively search all directories for .cpp files and compile them using gcc.

![image](https://github.com/agrnerd17/Breakout-Game/assets/18665288/3e098594-2d29-4bd5-b0ac-86c2b4f42f54)

I am hoping that this is just an issue with how I am compiling your code. It may be that it wasn't intended to run on linux.
Can you provide compilation instructions?

**Comment by agrnerd17** [comment]
Hi Bradley, 

Thank you for bringing this to my attention, the issue would most likely be with the Makefile and the Ubuntu version I currently have running on my computer. I have an older version of Ubuntu and as for the Makefile, those generally do not compile properly with gcc or clang++ compilers. Within the command line, you would have to type 'make build' to compile it properly. 

I am currently looking into this more, however, I am also working on a platform game using PyGame! I am planning on committing that to a repo by this weekend since I picked it up as a side project for fun during the Spring semester. 

Thanks,
Amelie

**Comment by bradleyGamiMarques** [comment]
Getting one step closer!
Thank you for providing the compilation instructions
When I ran `make build` in the root of the project I got an error saying that the compiler couldn't find
#include <X11/Xlib.h> that was imported in `Breakout-Game/tools/cpputils/graphics/cimg`

To get that file I had to run `sudo apt-get install libx11-dev`

After which when I ran `make build` I got the following.

```
make build
make[1]: Entering directory '/home/bradleymarques/source/Breakout-Game/tools/cppaudit'
make[1]: Leaving directory '/home/bradleymarques/source/Breakout-Game/tools/cppaudit'
```
And an executable binary named main was in the root of the project folder. I was able to click to start, but once I hit a block the game crashed with a Segmentation Fault. 😅 

I will close this issue with comment. Hope it helped. Looking forward to seeing what you come up with in PyGame!
I use RenPy for my visual novel project that I am working on.

**Comment by agrnerd17** [comment]
That sounds awesome! Looking forward to sharing my platformer game with you, it's kind of similar to an SNES Mario platform game but with different characters. I plan on fixing this game up or making a newer/more updated version of a breakout game, but I will let you know once those projects are completed. :) 

Thank you again for taking the time to look into my portfolio a bit more.

Thanks,
Amelie
